In [2]:
import pandas as pd
path = r"/Users/hendrikalbrecht/Dokumente/Z_Übungen/Mavenanalytics/coffee-shop-analysis/data/Coffee Shop Sales.xlsx"

df = pd.read_excel(path)

In [3]:
df.shape

(149116, 11)

In [4]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='str')

In [7]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[us]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
dtypes: datetime64[us](1), float64(1), int64(4), object(1), str(4)
memory usage: 12.5+ MB

In [9]:
df.isnull().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [10]:
df.nunique()

transaction_id      149116
transaction_date       181
transaction_time     25762
transaction_qty          6
store_id                 3
store_location           3
product_id              80
unit_price              41
product_category         9
product_type            29
product_detail          80
dtype: int64

Calculate revenue (quantity transactions * unit price)

In [11]:
df['revenue'] = df['transaction_qty'] * df['unit_price']

df['revenue'].sum()

round(df['revenue'].sum(), 2)

np.float64(698812.33)

Calculate number of transactions per store location

In [12]:
df['store_location'].value_counts()

store_location
Hell's Kitchen     50735
Astoria            50599
Lower Manhattan    47782
Name: count, dtype: int64

Calculate revenue per store location

In [13]:
df.groupby('store_location')['revenue'].sum()

store_location
Astoria            232243.91
Hell's Kitchen     236511.17
Lower Manhattan    230057.25
Name: revenue, dtype: float64

Group by product category and sort by revenue

In [14]:
df.groupby('product_category')['revenue'].sum().sort_values(ascending=False)

product_category
Coffee                269952.45
Tea                   196405.95
Bakery                 82315.64
Drinking Chocolate     72416.00
Coffee beans           40085.25
Branded                13607.00
Loose Tea              11213.60
Flavours                8408.80
Packaged Chocolate      4407.64
Name: revenue, dtype: float64

Number of Transactions by Product Type

In [15]:
df['product_type'].value_counts()

product_type
Brewed Chai tea          17183
Gourmet brewed coffee    16912
Barista Espresso         16403
Hot chocolate            11468
Brewed Black tea         11350
Brewed herbal tea        11245
Scone                    10173
Organic brewed coffee     8489
Drip coffee               8477
Premium brewed coffee     8135
Pastry                    6912
Biscotti                  5711
Brewed Green tea          5671
Regular syrup             4979
Sugar free syrup          1811
Housewares                 526
Chai tea                   443
Organic Beans              415
Gourmet Beans              366
Premium Beans              336
Espresso Beans             319
Herbal tea                 305
Black tea                  303
Drinking Chocolate         266
Organic Chocolate          221
Clothing                   221
House blend Beans          183
Green tea                  159
Green beans                134
Name: count, dtype: int64

Transactions per Store Location

In [16]:
df['store_location'].value_counts()

store_location
Hell's Kitchen     50735
Astoria            50599
Lower Manhattan    47782
Name: count, dtype: int64

Transactions per Product Category

In [17]:
df['product_category'].value_counts()

product_category
Coffee                58416
Tea                   45449
Bakery                22796
Drinking Chocolate    11468
Flavours               6790
Coffee beans           1753
Loose Tea              1210
Branded                 747
Packaged Chocolate      487
Name: count, dtype: int64

Product Category → Product Type Mapping

In [18]:
df[['product_category', 'product_type']].drop_duplicates().sort_values(['product_category', 'product_type'])

        product_category           product_type
22                Bakery               Biscotti
28                Bakery                 Pastry
5                 Bakery                  Scone
4598             Branded               Clothing
4033             Branded             Housewares
8                 Coffee       Barista Espresso
3                 Coffee            Drip coffee
0                 Coffee  Gourmet brewed coffee
31                Coffee  Organic brewed coffee
57                Coffee  Premium brewed coffee
3554        Coffee beans         Espresso Beans
3293        Coffee beans          Gourmet Beans
3519        Coffee beans            Green beans
4494        Coffee beans      House blend Beans
3296        Coffee beans          Organic Beans
3447        Coffee beans          Premium Beans
2     Drinking Chocolate          Hot chocolate
3254            Flavours          Regular syrup
3318            Flavours       Sugar free syrup
4288           Loose Tea              Black tea
3481           Loose Tea               Chai tea
3880           Loose Tea              Green tea
3263           Loose Tea             Herbal tea
3440  Packaged Chocolate     Drinking Chocolate
4022  Packaged Chocolate      Organic Chocolate
12                   Tea       Brewed Black tea
1                    Tea        Brewed Chai tea
15                   Tea       Brewed Green tea
17                   Tea      Brewed herbal tea

Average Revenue per Store Location

In [19]:
df.groupby('store_location')['revenue'].mean()

store_location
Astoria            4.589891
Hell's Kitchen     4.661696
Lower Manhattan    4.814726
Name: revenue, dtype: float64

Units Sold per Store Location

In [20]:
df.groupby('store_location')['transaction_qty'].sum()

store_location
Astoria            70991
Hell's Kitchen     71737
Lower Manhattan    71742
Name: transaction_qty, dtype: int64

Number of Unique Transaction IDs

In [21]:
df['transaction_id'].nunique()

149116

In [22]:
(df['transaction_id'].value_counts() > 1).sum()

np.int64(0)